name = "ChainsMakie"
uuid = "6238e05f-8c43-4d02-a7cb-3e4ed3b20087"
authors = ["simonsteiger <simon.j.steiger@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
MCMCChains = "6.0.7"
Makie = "0.22.4"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
